In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import pylab as pl
import numpy as np

%matplotlib inline

In [4]:
df = pd.read_csv("DATA-3-26.csv")
df.head()
df.describe()

,CS,FA,MA,BA,Pb,Sn,Sb,Bi,Br,I,Cl,Pero_Eg
count,1110.000000,1110.000000,1109.000000,1110.000000,1108.000000,1109.000000,1110.000000,1110.000000,948.000000,1104.000000,732.000000,588.000000
mean,0.170746,0.414552,0.420123,0.010514,0.858685,0.126787,0.008387,0.007820,0.578774,1.616222,1.158619,1.691706
std,0.328609,0.403326,0.427763,0.117558,0.300885,0.286251,0.123603,0.086174,0.615683,0.866113,0.722020,0.300108
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.170000
25%,0.000000,0.000000,0.000000,0.000000,0.980000,0.000000,0.000000,0.000000,0.030000,1.000000,0.000000,1.530000
50%,0.000000,0.400000,0.170000,0.000000,1.000000,0.000000,0.000000,0.000000,0.450000,1.000000,1.547500,1.620000
75%,0.150000,0.810000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,2.500000,1.621250,1.820000
max,1.000000,1.500000,1.000000,2.000000,1.100000,1.000000,2.000000,1.000000,2.400000,2.980000,2.400000,2.900000

In [ ]:
ndf = df[['Material','Space Group','Exp1','Exp2','EPBE','EGWG','Mean']]
ndf.head(9)

In [ ]:
msk = np.random.rand(len(ndf)) < 0.8

In [ ]:
train = ndf[msk]# plt.ylabel("GWg")
# plt.show()
test = ndf[~msk]

In [ ]:
plt.scatter(train.EPBE,train.EGWG, color = 'r' )
plt.xlabel("GWG")
plt.ylabel("PBE")
plt.show()

In [ ]:
# Regression
from sklearn import linear_model
regr = linear_model.LinearRegression()
train_x = np.asanyarray(train[['EPBE']])
train_y = np.asanyarray(train[['EGWG']])
regr.fit(train_x,train_y)
print("Coefficient : ", regr.coef_)
print("Intercept : ", regr.intercept_)
# print(train_x)
# plt.scatter(train_x,train_y, color = 'r')
# plt.xlabel("Egan")
# plt.ylabel("Epbe")
# plt.show()

In [ ]:
eol = regr.coef_[0][0]*train_x + regr.intercept_[0]
plt.scatter(train.EPBE, train.EGWG,  color='blue')
plt.plot(train_x, eol, 'r')
plt.xlabel("PBE")
plt.ylabel("GWG")
plt.show()

# plt.scatter(train_x, train_y, color = 'r')
# plt.scatter(train_x, regr.intercept_ + regr.coef_*train_x, color = 'blue')
# plt.xlabel("PBE")
# plt.ylabel("GWg")
# plt.show()

In [ ]:
# Prediction of y values on test set and Accuracy

from sklearn.metrics import r2_score
test_x = np.array(test[['EPBE']])
test_y = np.array(test[['EGWG']])
test_y_ = regr.predict(test_x)

print("MAE : %.2f" % np.mean(np.absolute(test_y_ - test_y)))
print("Residual sum of squares (MSE): %.2f" % np.mean((test_y_ - test_y) ** 2))
print("R2-score: %.2f" % r2_score(test_y , test_y_) )